name: ci

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-test:
    name: "Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "pypy-3.10"]

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
            python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          set -xe
          python -m pip install -r requirements_dev.txt
        shell: bash
      - name: "Build"
        run: |
          set -xe
          python -VV
          python setup.py sdist
          pip wheel --verbose --no-deps --no-clean dist/pyte*.tar.gz
          pip install pyte*.whl
        shell: bash
      - name: "Run tests"
        run: |
          set -xe
          # Change directory to avoid importing pyte from repo root.
          pushd tests
          python -m pytest -vv --pyargs .
          popd
        shell: bash
      - name: "Run mypy"
        run: |
          set -xe
          python -m pip install mypy==1.7.0
          python -m mypy --strict pyte
        shell: bash
